---
- name: Create SSL certs
  include_role:
    name: wazo-certs

- name: Workaround systemd
  file:
    src: /bin/true
    dest: /sbin/systemctl
    state: link
  when: not runtime

- name: Install Consul
  apt:
    name:
      - systemd
      - wazo-consul-config
    state: latest

- name: Remove generated files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/consul/master_token
    - /var/lib/consul/default_xivo_consul_token.yml
    - /var/lib/consul/default_xivo_consul_config.yml
    - /etc/consul.d/wazo-config.json
  when: not runtime

- name: Read exisiting token if any
  command: 'cat /var/lib/consul/master_token'
  register: wazo_consul_token
  ignore_errors: yes
  when: runtime

- name: Generate token
  shell: 'od -An -tx4 -N32 -w /dev/urandom | tr -d " "'
  register: wazo_consul_token_create
  when: runtime and wazo_consul_token.rc != 0

- name: Store token
  shell: 'echo "{{ wazo_consul_token_create.stdout }}" > /var/lib/consul/master_token'
  when: runtime and wazo_consul_token.rc != 0 and wazo_consul_token_create.rc == 0

- name: Read existing token
  command: 'cat /var/lib/consul/master_token'
  register: wazo_consul_token
  when: runtime

- name: Configure Consul access token in /etc/consul.d/wazo-config.json
  template:
    src: templates/wazo-config.json.j2
    dest: /etc/consul.d/wazo-config.json
  when: runtime

- name: Restart consul server
  systemd:
    name: consul
    state: restarted
    enabled: yes
  when: runtime
