version: '3'
services:
  consul_server:
    image: "wazopbx/wazo-consul"
    ports:
    - '9500:8500/tcp'
    - '9501:8501/tcp'
  message_bus:
    environment:
      WAZO_CONSUL_HOST: consul_server
      WAZO_CONSUL_PORT: 8501
      WAZO_CONSUL_SCHEME: https
    image: "wazopbx/wazo-message-bus"
    ports:
    - '5672:5672'
