debian_upgrade_first: true

wazo_debian_repo: main
wazo_debian_repo_upgrade: main
wazo_distribution: wazo-dev-buster
wazo_distribution_upgrade: wazo-dev-buster

engine_api_host: localhost
engine_api_port: 443
engine_api_tracing: false
engine_language: en_US

api_client_name: api-client
api_client_password: api-password
engine_api_configure_wizard: false
tenant_name: my-company

engine_auth_path: /api/auth/0.1
engine_confd_path: /api/confd/1.1
engine_setupd_path: /api/setupd/1.0

# router_advertise_address: democ4.wazo.community
# router_advertise_port: 5060
router_api_endpoint_confd: http://localhost:8000
router_api_db_host: localhost
router_api_db_port: 5432
router_api_db_name: wazo_router_confd
router_api_db_user: wazo_router_confd
router_api_db_password: wazo_router_confd
router_api_redis_host: localhost
router_api_redis_port: 6379
router_api_redis_database: 1
router_interface: "{{ ansible_default_ipv4.interface }}"
router_redis_dialog: 1
router_dburl_dialog: redis://localhost:6379/2

rtpengine_interface: "{{ ansible_default_ipv4.interface }}"
rtpengine_private_address: "{{ ansible_default_ipv4.address }}"
rtpengine_public_address: "{{ ansible_default_ipv4.address }}"
rtpengine_listen_ng: "22222"
rtpengine_port_min: "23000"
rtpengine_port_max: "32768"

runtime: true

# sbc_advertise_address: democ4.wazo.community
# sbc_advertise_port: 5060
sbc_interface: "{{ ansible_default_ipv4.interface }}"
sbc_dispatcher_list: "1 sip:localhost:5060 16 10"
sbc_redis_dialog: 1
sbc_dburl_dialog: redis://localhost:6379/3

wazo_consul_host: localhost
wazo_consul_port: 8500
wazo_consul_scheme: http
wazo_consul_datacenter: wazo-platform

###################################################################################
# The following variables must only be set for a customized value. The default
# value (written in the comment) is handled by Debian packaging and subject to
# change.
###################################################################################

# wazo_locale: en_US.UTF-8

# engine_api_db_host: localhost
# engine_api_db_port: 5432
# engine_api_listen_address: 127.0.0.1

# engine_api_port_confgend: 8669

# engine_api_db_confd_name: asterisk
# engine_api_db_confd_password: proformatique
# engine_api_db_confd_user: asterisk

# engine_api_db_admin_password:
# engine_api_db_admin_user: postgres

# engine_api_db_auth_name: asterisk
# engine_api_db_auth_password: proformatique
# engine_api_db_auth_user: asterisk

# b2bua_ami_permit_client_address: 127.0.0.1
# b2bua_ami_permit_client_mask: 255.255.255.255
# b2bua_host: localhost
# b2bua_listen_address: 127.0.0.1
# b2bua_port_ami: 5038
# b2bua_port_http: 5039
# b2bua_port_https: 5040
# b2bua_port_sysconfd: 8668

# ari_password: Nasheow8Eag
# ari_username: xivo

# ami_password: eeCho8ied3u
# ami_username: wazo_amid
