- name: Install needed package for switching to non privileged user
  apt:
    name:
      - acl
      - sudo
    state: latest

- name: Create router-confd PostgreSQL database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ router_api_db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Create router-confd PostgreSQL user
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ router_api_db_name }}"
    name: "{{ router_api_db_user }}"
    password: "{{ router_api_db_password }}"
    priv: "ALL"
